version: 2.1

jobs:
  build:
    docker:
      - image: alexfalkowski/ruby:3.3
    working_directory: ~/alexfalkowski
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - restore_cache:
          name: restore deps
          keys:
            - alexfalkowski-ruby-cache-{{ checksum "Gemfile.lock" }}
            - alexfalkowski-ruby-cache-
      - run: make dep
      - save_cache:
          name: save deps
          key: alexfalkowski-ruby-cache-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor
      - run: make lint
    resource_class: large
  release:
    docker:
      - image: alexfalkowski/release:3.1
    working_directory: ~/alexfalkowski
    steps:
      - checkout
      - run: release
    resource_class: large

workflows:
  alexfalkowski:
    jobs:
      - build
      - release:
          context: gh
          requires:
            - build
          filters:
            branches:
              only: master
