version: 2.1

jobs:
  build:
    docker:
      - image: alexfalkowski/ruby:1.60
    working_directory: ~/alexfalkowski
    steps:
      - checkout:
          method: blobless
      - run: git submodule sync
      - run: git submodule update --init
      - run: make source-key
      - restore_cache:
          name: restore deps
          keys:
            - alexfalkowski-ruby-cache-{{ checksum "Gemfile.lock" }}-{{ checksum "~/.ruby-version" }}-{{ checksum ".source-key" }}
            - alexfalkowski-ruby-cache-
      - run: make dep
      - run: make clean-dep
      - save_cache:
          name: save deps
          key: alexfalkowski-ruby-cache-{{ checksum "Gemfile.lock" }}-{{ checksum "~/.ruby-version" }}-{{ checksum ".source-key" }}
          paths:
            - vendor
      - run: make lint
    resource_class: large
  version:
    docker:
      - image: alexfalkowski/release:5.17
    working_directory: ~/alexfalkowski
    steps:
      - checkout:
          method: blobless
      - run: git submodule sync
      - run: git submodule update --init
      - run: version
    resource_class: large

workflows:
  alexfalkowski:
    jobs:
      - build
      - version:
          context: gh
          requires:
            - build
          filters:
            branches:
              only: master
